version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    #restart: always
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: springDemo
      MYSQL_ROOT_PASSWORD: ""   # insecure, ok for dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

volumes:
  mysql_data:
